{
 "title": "Dynamic Bandwidth",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bytes Injected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "db_total_messages{injector=\"injector\",size=\"size\"}",
     "legendFormat": "Message Size"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "db_total_messages{sender=\"sender\",size=\"size\"}",
     "legendFormat": "Message Size"
    }
   ]
  },
  {
   "title": "Messages Injected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "db_plot_messages{﻿﻿﻿count﻿﻿=﻿﻿\"count\"﻿﻿,injector=\"injector\"﻿﻿}",
     "legendFormat": "Plot"
    },
    {
     "expr": "db_track_messages{count=\"count\",injector=\"injector\"}",
     "legendFormat": "Track"
    },
    {
     "expr": "db_mission_status_messages{count=\"count\",injector=\"injector\"}",
     "legendFormat": "Mission Status"
    },
    {
     "expr": "db_sensor_status_messages{count=\"count\",injector=\"injector\"}",
     "legendFormat": "Sensor Status"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "db_plot_messages{count=\"count\",sender=\"sender\"}",
     "legendFormat": "Plot"
    },
    {
     "expr": "db_track_messages{count=\"count\",sender=\"sender\"}",
     "legendFormat": "Track"
    },
    {
     "expr": "db_mission_status_messages{count=\"count\",sender=\"sender\"}",
     "legendFormat": "Mission Status"
    },
    {
     "expr": "db_sensor_status_messages{count=\"count\",sender=\"sender\"}",
     "legendFormat": "Sensor Status"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "db_processing_time" }
   ]
  }
 ]
}