apiVersion: apps/v1

kind: Deployment

metadata:
  name: bw-handler-4-deployment
  labels:
    app: bw-handler-4

spec:

  replicas: 1

  selector:

    matchLabels:

      app: bw-handler-4

  template:

    metadata:

      labels:

        app: bw-handler-4

    spec:

      containers:

      - name: bw-handler-4

        image: me-west1-docker.pkg.dev/team12-380616/bw-management-docker-repo/bw-handler-image:v1.0.0
        env:
          - name: "ConnectionStrings__REDIS_CONNECTION_STRING"
            value: "redis://34.165.78.173:6379"
          - name: "DataHandlerConfig__RedisConnectionMultiplexer"
            value: "34.165.78.173"
          - name: "RunningChannelID"
            value: "4"

     
